// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Notifications.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The response schema for the deleteDestination operation.
    /// </summary>
    public partial class DeleteDestinationResponse
    {
        /// <summary>
        /// Initializes a new instance of the DeleteDestinationResponse class.
        /// </summary>
        public DeleteDestinationResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeleteDestinationResponse class.
        /// </summary>
        /// <param name="errors">One or more unexpected errors occurred during
        /// the deleteDestination operation.</param>
        public DeleteDestinationResponse(IList<Error> errors = default(IList<Error>))
        {
            Errors = errors;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets one or more unexpected errors occurred during the
        /// deleteDestination operation.
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<Error> Errors { get; set; }

    }
}
