// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Finances.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// An adjustment to the seller's account.
    /// </summary>
    public partial class AdjustmentEvent
    {
        /// <summary>
        /// Initializes a new instance of the AdjustmentEvent class.
        /// </summary>
        public AdjustmentEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AdjustmentEvent class.
        /// </summary>
        /// <param name="adjustmentType">The type of adjustment.
        ///
        /// Possible values:
        ///
        /// * FBAInventoryReimbursement - An FBA inventory reimbursement to a
        /// seller's account. This occurs if a seller's inventory is damaged.
        ///
        /// * ReserveEvent - A reserve event that is generated at the time of a
        /// settlement period closing. This occurs when some money from a
        /// seller's account is held back.
        ///
        /// * PostageBilling - The amount paid by a seller for shipping labels.
        ///
        /// * PostageRefund - The reimbursement of shipping labels purchased
        /// for orders that were canceled or refunded.
        ///
        /// * LostOrDamagedReimbursement - An Amazon Easy Ship reimbursement to
        /// a seller's account for a package that we lost or damaged.
        ///
        /// * CanceledButPickedUpReimbursement - An Amazon Easy Ship
        /// reimbursement to a seller's account. This occurs when a package is
        /// picked up and the order is subsequently canceled. This value is
        /// used only in the India marketplace.
        ///
        /// * ReimbursementClawback - An Amazon Easy Ship reimbursement
        /// clawback from a seller's account. This occurs when a prior
        /// reimbursement is reversed. This value is used only in the India
        /// marketplace.
        ///
        /// * SellerRewards - An award credited to a seller's account for their
        /// participation in an offer in the Seller Rewards program. Applies
        /// only to the India marketplace.</param>
        /// <param name="postedDate">The date and time when the financial event
        /// was posted.</param>
        /// <param name="adjustmentAmount">The amount adjusted as part of this
        /// event.</param>
        /// <param name="adjustmentItemList">A list of information about
        /// adjustments to an account.</param>
        public AdjustmentEvent(string adjustmentType = default(string), System.DateTime? postedDate = default(System.DateTime?), Currency adjustmentAmount = default(Currency), IList<AdjustmentItem> adjustmentItemList = default(IList<AdjustmentItem>))
        {
            AdjustmentType = adjustmentType;
            PostedDate = postedDate;
            AdjustmentAmount = adjustmentAmount;
            AdjustmentItemList = adjustmentItemList;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the type of adjustment.
        ///
        /// Possible values:
        ///
        /// * FBAInventoryReimbursement - An FBA inventory reimbursement to a
        /// seller's account. This occurs if a seller's inventory is damaged.
        ///
        /// * ReserveEvent - A reserve event that is generated at the time of a
        /// settlement period closing. This occurs when some money from a
        /// seller's account is held back.
        ///
        /// * PostageBilling - The amount paid by a seller for shipping labels.
        ///
        /// * PostageRefund - The reimbursement of shipping labels purchased
        /// for orders that were canceled or refunded.
        ///
        /// * LostOrDamagedReimbursement - An Amazon Easy Ship reimbursement to
        /// a seller's account for a package that we lost or damaged.
        ///
        /// * CanceledButPickedUpReimbursement - An Amazon Easy Ship
        /// reimbursement to a seller's account. This occurs when a package is
        /// picked up and the order is subsequently canceled. This value is
        /// used only in the India marketplace.
        ///
        /// * ReimbursementClawback - An Amazon Easy Ship reimbursement
        /// clawback from a seller's account. This occurs when a prior
        /// reimbursement is reversed. This value is used only in the India
        /// marketplace.
        ///
        /// * SellerRewards - An award credited to a seller's account for their
        /// participation in an offer in the Seller Rewards program. Applies
        /// only to the India marketplace.
        /// </summary>
        [JsonProperty(PropertyName = "AdjustmentType")]
        public string AdjustmentType { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the financial event was posted.
        /// </summary>
        [JsonProperty(PropertyName = "PostedDate")]
        public System.DateTime? PostedDate { get; set; }

        /// <summary>
        /// Gets or sets the amount adjusted as part of this event.
        /// </summary>
        [JsonProperty(PropertyName = "AdjustmentAmount")]
        public Currency AdjustmentAmount { get; set; }

        /// <summary>
        /// Gets or sets a list of information about adjustments to an account.
        /// </summary>
        [JsonProperty(PropertyName = "AdjustmentItemList")]
        public IList<AdjustmentItem> AdjustmentItemList { get; set; }

    }
}
