// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Finances.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A payment event for Fulfillment by Amazon (FBA) inventory liquidation.
    /// This event is used only in the US marketplace.
    /// </summary>
    public partial class FBALiquidationEvent
    {
        /// <summary>
        /// Initializes a new instance of the FBALiquidationEvent class.
        /// </summary>
        public FBALiquidationEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FBALiquidationEvent class.
        /// </summary>
        /// <param name="postedDate">The date and time when the financial event
        /// was posted.</param>
        /// <param name="originalRemovalOrderId">The identifier for the
        /// original removal order.</param>
        /// <param name="liquidationProceedsAmount">The amount paid by the
        /// liquidator for the seller's inventory. The seller receives this
        /// amount minus LiquidationFeeAmount.</param>
        /// <param name="liquidationFeeAmount">The fee charged to the seller by
        /// Amazon for liquidating the seller's FBA inventory.</param>
        public FBALiquidationEvent(System.DateTime? postedDate = default(System.DateTime?), string originalRemovalOrderId = default(string), Currency liquidationProceedsAmount = default(Currency), Currency liquidationFeeAmount = default(Currency))
        {
            PostedDate = postedDate;
            OriginalRemovalOrderId = originalRemovalOrderId;
            LiquidationProceedsAmount = liquidationProceedsAmount;
            LiquidationFeeAmount = liquidationFeeAmount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the date and time when the financial event was posted.
        /// </summary>
        [JsonProperty(PropertyName = "PostedDate")]
        public System.DateTime? PostedDate { get; set; }

        /// <summary>
        /// Gets or sets the identifier for the original removal order.
        /// </summary>
        [JsonProperty(PropertyName = "OriginalRemovalOrderId")]
        public string OriginalRemovalOrderId { get; set; }

        /// <summary>
        /// Gets or sets the amount paid by the liquidator for the seller's
        /// inventory. The seller receives this amount minus
        /// LiquidationFeeAmount.
        /// </summary>
        [JsonProperty(PropertyName = "LiquidationProceedsAmount")]
        public Currency LiquidationProceedsAmount { get; set; }

        /// <summary>
        /// Gets or sets the fee charged to the seller by Amazon for
        /// liquidating the seller's FBA inventory.
        /// </summary>
        [JsonProperty(PropertyName = "LiquidationFeeAmount")]
        public Currency LiquidationFeeAmount { get; set; }

    }
}
