// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Finances.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A fee event related to Amazon Imaging services.
    /// </summary>
    public partial class ImagingServicesFeeEvent
    {
        /// <summary>
        /// Initializes a new instance of the ImagingServicesFeeEvent class.
        /// </summary>
        public ImagingServicesFeeEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImagingServicesFeeEvent class.
        /// </summary>
        /// <param name="imagingRequestBillingItemID">The identifier for the
        /// imaging services request.</param>
        /// <param name="aSIN">The Amazon Standard Identification Number (ASIN)
        /// of the item for which the imaging service was requested.</param>
        /// <param name="postedDate">The date and time when the financial event
        /// was posted.</param>
        /// <param name="feeList">A list of fees associated with the
        /// event.</param>
        public ImagingServicesFeeEvent(string imagingRequestBillingItemID = default(string), string aSIN = default(string), System.DateTime? postedDate = default(System.DateTime?), IList<FeeComponent> feeList = default(IList<FeeComponent>))
        {
            ImagingRequestBillingItemID = imagingRequestBillingItemID;
            ASIN = aSIN;
            PostedDate = postedDate;
            FeeList = feeList;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the identifier for the imaging services request.
        /// </summary>
        [JsonProperty(PropertyName = "ImagingRequestBillingItemID")]
        public string ImagingRequestBillingItemID { get; set; }

        /// <summary>
        /// Gets or sets the Amazon Standard Identification Number (ASIN) of
        /// the item for which the imaging service was requested.
        /// </summary>
        [JsonProperty(PropertyName = "ASIN")]
        public string ASIN { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the financial event was posted.
        /// </summary>
        [JsonProperty(PropertyName = "PostedDate")]
        public System.DateTime? PostedDate { get; set; }

        /// <summary>
        /// Gets or sets a list of fees associated with the event.
        /// </summary>
        [JsonProperty(PropertyName = "FeeList")]
        public IList<FeeComponent> FeeList { get; set; }

    }
}
