// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Finances.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A removal shipment event for a removal order.
    /// </summary>
    public partial class RemovalShipmentEvent
    {
        /// <summary>
        /// Initializes a new instance of the RemovalShipmentEvent class.
        /// </summary>
        public RemovalShipmentEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RemovalShipmentEvent class.
        /// </summary>
        /// <param name="postedDate">The date and time when the financial event
        /// was posted.</param>
        /// <param name="orderId">The identifier for the removal shipment
        /// order.</param>
        /// <param name="transactionType">The type of removal order.
        ///
        /// Possible values:
        ///
        /// * WHOLESALE_LIQUIDATION</param>
        /// <param name="removalShipmentItemList">A list of removal shipment
        /// items.</param>
        public RemovalShipmentEvent(System.DateTime? postedDate = default(System.DateTime?), string orderId = default(string), string transactionType = default(string), IList<RemovalShipmentItem> removalShipmentItemList = default(IList<RemovalShipmentItem>))
        {
            PostedDate = postedDate;
            OrderId = orderId;
            TransactionType = transactionType;
            RemovalShipmentItemList = removalShipmentItemList;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the date and time when the financial event was posted.
        /// </summary>
        [JsonProperty(PropertyName = "PostedDate")]
        public System.DateTime? PostedDate { get; set; }

        /// <summary>
        /// Gets or sets the identifier for the removal shipment order.
        /// </summary>
        [JsonProperty(PropertyName = "OrderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// Gets or sets the type of removal order.
        ///
        /// Possible values:
        ///
        /// * WHOLESALE_LIQUIDATION
        /// </summary>
        [JsonProperty(PropertyName = "TransactionType")]
        public string TransactionType { get; set; }

        /// <summary>
        /// Gets or sets a list of removal shipment items.
        /// </summary>
        [JsonProperty(PropertyName = "RemovalShipmentItemList")]
        public IList<RemovalShipmentItem> RemovalShipmentItemList { get; set; }

    }
}
