// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Finances.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// An event related to a rental transaction.
    /// </summary>
    public partial class RentalTransactionEvent
    {
        /// <summary>
        /// Initializes a new instance of the RentalTransactionEvent class.
        /// </summary>
        public RentalTransactionEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RentalTransactionEvent class.
        /// </summary>
        /// <param name="amazonOrderId">An Amazon-defined identifier for an
        /// order.</param>
        /// <param name="rentalEventType">The type of rental event.
        ///
        /// Possible values:
        ///
        /// * RentalCustomerPayment-Buyout - Transaction type that represents
        /// when the customer wants to buy out a rented item.
        ///
        /// * RentalCustomerPayment-Extension - Transaction type that
        /// represents when the customer wants to extend the rental period.
        ///
        /// * RentalCustomerRefund-Buyout - Transaction type that represents
        /// when the customer requests a refund for the buyout of the rented
        /// item.
        ///
        /// * RentalCustomerRefund-Extension - Transaction type that represents
        /// when the customer requests a refund over the extension on the
        /// rented item.
        ///
        /// * RentalHandlingFee - Transaction type that represents the fee that
        /// Amazon charges sellers who rent through Amazon.
        ///
        /// * RentalChargeFailureReimbursement - Transaction type that
        /// represents when Amazon sends money to the seller to compensate for
        /// a failed charge.
        ///
        /// * RentalLostItemReimbursement - Transaction type that represents
        /// when Amazon sends money to the seller to compensate for a lost
        /// item.</param>
        /// <param name="extensionLength">The number of days that the buyer
        /// extended an already rented item. This value is only returned for
        /// RentalCustomerPayment-Extension and RentalCustomerRefund-Extension
        /// events.</param>
        /// <param name="postedDate">The date and time when the financial event
        /// was posted.</param>
        /// <param name="rentalChargeList">A list of charges associated with
        /// the rental event.</param>
        /// <param name="rentalFeeList">A list of fees associated with the
        /// rental event.</param>
        /// <param name="marketplaceName">The name of the marketplace.</param>
        /// <param name="rentalInitialValue">The amount of money the customer
        /// originally paid to rent the item. This value is only returned for
        /// RentalChargeFailureReimbursement and RentalLostItemReimbursement
        /// events.</param>
        /// <param name="rentalReimbursement">The amount of money Amazon sends
        /// the seller to compensate for a lost item or a failed charge. This
        /// value is only returned for RentalChargeFailureReimbursement and
        /// RentalLostItemReimbursement events.</param>
        /// <param name="rentalTaxWithheldList">A list of taxes withheld
        /// information for a rental item.</param>
        public RentalTransactionEvent(string amazonOrderId = default(string), string rentalEventType = default(string), int? extensionLength = default(int?), System.DateTime? postedDate = default(System.DateTime?), IList<ChargeComponent> rentalChargeList = default(IList<ChargeComponent>), IList<FeeComponent> rentalFeeList = default(IList<FeeComponent>), string marketplaceName = default(string), Currency rentalInitialValue = default(Currency), Currency rentalReimbursement = default(Currency), IList<TaxWithheldComponent> rentalTaxWithheldList = default(IList<TaxWithheldComponent>))
        {
            AmazonOrderId = amazonOrderId;
            RentalEventType = rentalEventType;
            ExtensionLength = extensionLength;
            PostedDate = postedDate;
            RentalChargeList = rentalChargeList;
            RentalFeeList = rentalFeeList;
            MarketplaceName = marketplaceName;
            RentalInitialValue = rentalInitialValue;
            RentalReimbursement = rentalReimbursement;
            RentalTaxWithheldList = rentalTaxWithheldList;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets an Amazon-defined identifier for an order.
        /// </summary>
        [JsonProperty(PropertyName = "AmazonOrderId")]
        public string AmazonOrderId { get; set; }

        /// <summary>
        /// Gets or sets the type of rental event.
        ///
        /// Possible values:
        ///
        /// * RentalCustomerPayment-Buyout - Transaction type that represents
        /// when the customer wants to buy out a rented item.
        ///
        /// * RentalCustomerPayment-Extension - Transaction type that
        /// represents when the customer wants to extend the rental period.
        ///
        /// * RentalCustomerRefund-Buyout - Transaction type that represents
        /// when the customer requests a refund for the buyout of the rented
        /// item.
        ///
        /// * RentalCustomerRefund-Extension - Transaction type that represents
        /// when the customer requests a refund over the extension on the
        /// rented item.
        ///
        /// * RentalHandlingFee - Transaction type that represents the fee that
        /// Amazon charges sellers who rent through Amazon.
        ///
        /// * RentalChargeFailureReimbursement - Transaction type that
        /// represents when Amazon sends money to the seller to compensate for
        /// a failed charge.
        ///
        /// * RentalLostItemReimbursement - Transaction type that represents
        /// when Amazon sends money to the seller to compensate for a lost
        /// item.
        /// </summary>
        [JsonProperty(PropertyName = "RentalEventType")]
        public string RentalEventType { get; set; }

        /// <summary>
        /// Gets or sets the number of days that the buyer extended an already
        /// rented item. This value is only returned for
        /// RentalCustomerPayment-Extension and RentalCustomerRefund-Extension
        /// events.
        /// </summary>
        [JsonProperty(PropertyName = "ExtensionLength")]
        public int? ExtensionLength { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the financial event was posted.
        /// </summary>
        [JsonProperty(PropertyName = "PostedDate")]
        public System.DateTime? PostedDate { get; set; }

        /// <summary>
        /// Gets or sets a list of charges associated with the rental event.
        /// </summary>
        [JsonProperty(PropertyName = "RentalChargeList")]
        public IList<ChargeComponent> RentalChargeList { get; set; }

        /// <summary>
        /// Gets or sets a list of fees associated with the rental event.
        /// </summary>
        [JsonProperty(PropertyName = "RentalFeeList")]
        public IList<FeeComponent> RentalFeeList { get; set; }

        /// <summary>
        /// Gets or sets the name of the marketplace.
        /// </summary>
        [JsonProperty(PropertyName = "MarketplaceName")]
        public string MarketplaceName { get; set; }

        /// <summary>
        /// Gets or sets the amount of money the customer originally paid to
        /// rent the item. This value is only returned for
        /// RentalChargeFailureReimbursement and RentalLostItemReimbursement
        /// events.
        /// </summary>
        [JsonProperty(PropertyName = "RentalInitialValue")]
        public Currency RentalInitialValue { get; set; }

        /// <summary>
        /// Gets or sets the amount of money Amazon sends the seller to
        /// compensate for a lost item or a failed charge. This value is only
        /// returned for RentalChargeFailureReimbursement and
        /// RentalLostItemReimbursement events.
        /// </summary>
        [JsonProperty(PropertyName = "RentalReimbursement")]
        public Currency RentalReimbursement { get; set; }

        /// <summary>
        /// Gets or sets a list of taxes withheld information for a rental
        /// item.
        /// </summary>
        [JsonProperty(PropertyName = "RentalTaxWithheldList")]
        public IList<TaxWithheldComponent> RentalTaxWithheldList { get; set; }

    }
}
