// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Finances.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An event linked to the payment of a fee related to the specified deal.
    /// </summary>
    public partial class SellerDealPaymentEvent
    {
        /// <summary>
        /// Initializes a new instance of the SellerDealPaymentEvent class.
        /// </summary>
        public SellerDealPaymentEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SellerDealPaymentEvent class.
        /// </summary>
        /// <param name="postedDate">The date and time when the financial event
        /// was posted.</param>
        /// <param name="dealId">The unique identifier of the deal.</param>
        /// <param name="dealDescription">The internal description of the
        /// deal.</param>
        /// <param name="eventType">The type of event:
        /// SellerDealComplete.</param>
        /// <param name="feeType">The type of fee: RunLightningDealFee.</param>
        /// <param name="feeAmount">The monetary amount of the fee.</param>
        /// <param name="taxAmount">The monetary amount of the tax
        /// applied.</param>
        /// <param name="totalAmount">The total monetary amount paid.</param>
        public SellerDealPaymentEvent(System.DateTime? postedDate = default(System.DateTime?), string dealId = default(string), string dealDescription = default(string), string eventType = default(string), string feeType = default(string), Currency feeAmount = default(Currency), Currency taxAmount = default(Currency), Currency totalAmount = default(Currency))
        {
            PostedDate = postedDate;
            DealId = dealId;
            DealDescription = dealDescription;
            EventType = eventType;
            FeeType = feeType;
            FeeAmount = feeAmount;
            TaxAmount = taxAmount;
            TotalAmount = totalAmount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the date and time when the financial event was posted.
        /// </summary>
        [JsonProperty(PropertyName = "postedDate")]
        public System.DateTime? PostedDate { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the deal.
        /// </summary>
        [JsonProperty(PropertyName = "dealId")]
        public string DealId { get; set; }

        /// <summary>
        /// Gets or sets the internal description of the deal.
        /// </summary>
        [JsonProperty(PropertyName = "dealDescription")]
        public string DealDescription { get; set; }

        /// <summary>
        /// Gets or sets the type of event: SellerDealComplete.
        /// </summary>
        [JsonProperty(PropertyName = "eventType")]
        public string EventType { get; set; }

        /// <summary>
        /// Gets or sets the type of fee: RunLightningDealFee.
        /// </summary>
        [JsonProperty(PropertyName = "feeType")]
        public string FeeType { get; set; }

        /// <summary>
        /// Gets or sets the monetary amount of the fee.
        /// </summary>
        [JsonProperty(PropertyName = "feeAmount")]
        public Currency FeeAmount { get; set; }

        /// <summary>
        /// Gets or sets the monetary amount of the tax applied.
        /// </summary>
        [JsonProperty(PropertyName = "taxAmount")]
        public Currency TaxAmount { get; set; }

        /// <summary>
        /// Gets or sets the total monetary amount paid.
        /// </summary>
        [JsonProperty(PropertyName = "totalAmount")]
        public Currency TotalAmount { get; set; }

    }
}
