// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Finances.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A shipment, refund, guarantee claim, or chargeback.
    /// </summary>
    public partial class ShipmentEvent
    {
        /// <summary>
        /// Initializes a new instance of the ShipmentEvent class.
        /// </summary>
        public ShipmentEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ShipmentEvent class.
        /// </summary>
        /// <param name="amazonOrderId">An Amazon-defined identifier for an
        /// order.</param>
        /// <param name="sellerOrderId">A seller-defined identifier for an
        /// order.</param>
        /// <param name="marketplaceName">The name of the marketplace where the
        /// event occurred.</param>
        /// <param name="orderChargeList">A list of order-level charges. These
        /// charges are applicable to Multi-Channel Fulfillment COD
        /// orders.</param>
        /// <param name="orderChargeAdjustmentList">A list of order-level
        /// charge adjustments. These adjustments are applicable to
        /// Multi-Channel Fulfillment COD orders.</param>
        /// <param name="shipmentFeeList">A list of shipment-level
        /// fees.</param>
        /// <param name="shipmentFeeAdjustmentList">A list of shipment-level
        /// fee adjustments.</param>
        /// <param name="orderFeeList">A list of order-level fees. These
        /// charges are applicable to Multi-Channel Fulfillment orders.</param>
        /// <param name="orderFeeAdjustmentList">A list of order-level fee
        /// adjustments. These adjustments are applicable to Multi-Channel
        /// Fulfillment orders.</param>
        /// <param name="directPaymentList">A list of transactions where buyers
        /// pay Amazon through one of the credit cards offered by Amazon or
        /// where buyers pay a seller directly through COD.</param>
        /// <param name="postedDate">The date and time when the financial event
        /// was posted.</param>
        /// <param name="shipmentItemAdjustmentList">A list of shipment item
        /// adjustments.</param>
        public ShipmentEvent(string amazonOrderId = default(string), string sellerOrderId = default(string), string marketplaceName = default(string), IList<ChargeComponent> orderChargeList = default(IList<ChargeComponent>), IList<ChargeComponent> orderChargeAdjustmentList = default(IList<ChargeComponent>), IList<FeeComponent> shipmentFeeList = default(IList<FeeComponent>), IList<FeeComponent> shipmentFeeAdjustmentList = default(IList<FeeComponent>), IList<FeeComponent> orderFeeList = default(IList<FeeComponent>), IList<FeeComponent> orderFeeAdjustmentList = default(IList<FeeComponent>), IList<DirectPayment> directPaymentList = default(IList<DirectPayment>), System.DateTime? postedDate = default(System.DateTime?), IList<ShipmentItem> shipmentItemList = default(IList<ShipmentItem>), IList<ShipmentItem> shipmentItemAdjustmentList = default(IList<ShipmentItem>))
        {
            AmazonOrderId = amazonOrderId;
            SellerOrderId = sellerOrderId;
            MarketplaceName = marketplaceName;
            OrderChargeList = orderChargeList;
            OrderChargeAdjustmentList = orderChargeAdjustmentList;
            ShipmentFeeList = shipmentFeeList;
            ShipmentFeeAdjustmentList = shipmentFeeAdjustmentList;
            OrderFeeList = orderFeeList;
            OrderFeeAdjustmentList = orderFeeAdjustmentList;
            DirectPaymentList = directPaymentList;
            PostedDate = postedDate;
            ShipmentItemList = shipmentItemList;
            ShipmentItemAdjustmentList = shipmentItemAdjustmentList;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets an Amazon-defined identifier for an order.
        /// </summary>
        [JsonProperty(PropertyName = "AmazonOrderId")]
        public string AmazonOrderId { get; set; }

        /// <summary>
        /// Gets or sets a seller-defined identifier for an order.
        /// </summary>
        [JsonProperty(PropertyName = "SellerOrderId")]
        public string SellerOrderId { get; set; }

        /// <summary>
        /// Gets or sets the name of the marketplace where the event occurred.
        /// </summary>
        [JsonProperty(PropertyName = "MarketplaceName")]
        public string MarketplaceName { get; set; }

        /// <summary>
        /// Gets or sets a list of order-level charges. These charges are
        /// applicable to Multi-Channel Fulfillment COD orders.
        /// </summary>
        [JsonProperty(PropertyName = "OrderChargeList")]
        public IList<ChargeComponent> OrderChargeList { get; set; }

        /// <summary>
        /// Gets or sets a list of order-level charge adjustments. These
        /// adjustments are applicable to Multi-Channel Fulfillment COD orders.
        /// </summary>
        [JsonProperty(PropertyName = "OrderChargeAdjustmentList")]
        public IList<ChargeComponent> OrderChargeAdjustmentList { get; set; }

        /// <summary>
        /// Gets or sets a list of shipment-level fees.
        /// </summary>
        [JsonProperty(PropertyName = "ShipmentFeeList")]
        public IList<FeeComponent> ShipmentFeeList { get; set; }

        /// <summary>
        /// Gets or sets a list of shipment-level fee adjustments.
        /// </summary>
        [JsonProperty(PropertyName = "ShipmentFeeAdjustmentList")]
        public IList<FeeComponent> ShipmentFeeAdjustmentList { get; set; }

        /// <summary>
        /// Gets or sets a list of order-level fees. These charges are
        /// applicable to Multi-Channel Fulfillment orders.
        /// </summary>
        [JsonProperty(PropertyName = "OrderFeeList")]
        public IList<FeeComponent> OrderFeeList { get; set; }

        /// <summary>
        /// Gets or sets a list of order-level fee adjustments. These
        /// adjustments are applicable to Multi-Channel Fulfillment orders.
        /// </summary>
        [JsonProperty(PropertyName = "OrderFeeAdjustmentList")]
        public IList<FeeComponent> OrderFeeAdjustmentList { get; set; }

        /// <summary>
        /// Gets or sets a list of transactions where buyers pay Amazon through
        /// one of the credit cards offered by Amazon or where buyers pay a
        /// seller directly through COD.
        /// </summary>
        [JsonProperty(PropertyName = "DirectPaymentList")]
        public IList<DirectPayment> DirectPaymentList { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the financial event was posted.
        /// </summary>
        [JsonProperty(PropertyName = "PostedDate")]
        public System.DateTime? PostedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShipmentItemList")]
        public IList<ShipmentItem> ShipmentItemList { get; set; }

        /// <summary>
        /// Gets or sets a list of shipment item adjustments.
        /// </summary>
        [JsonProperty(PropertyName = "ShipmentItemAdjustmentList")]
        public IList<ShipmentItem> ShipmentItemAdjustmentList { get; set; }

    }
}
