// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Tokens.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The response schema for the createRestrictedDataToken operation.
    /// </summary>
    public partial class CreateRestrictedDataTokenResponse
    {
        /// <summary>
        /// Initializes a new instance of the CreateRestrictedDataTokenResponse
        /// class.
        /// </summary>
        public CreateRestrictedDataTokenResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateRestrictedDataTokenResponse
        /// class.
        /// </summary>
        /// <param name="restrictedDataToken">A Restricted Data Token (RDT).
        /// This is a short-lived access token that authorizes you to access
        /// the restricted resources that you specified. Pass this value with
        /// the x-amzn-access-token header when making subsequent calls to
        /// these restricted resources.</param>
        /// <param name="expiresIn">The lifetime of the Restricted Data Token,
        /// in seconds.</param>
        public CreateRestrictedDataTokenResponse(string restrictedDataToken = default(string), int? expiresIn = default(int?))
        {
            RestrictedDataToken = restrictedDataToken;
            ExpiresIn = expiresIn;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a Restricted Data Token (RDT). This is a short-lived
        /// access token that authorizes you to access the restricted resources
        /// that you specified. Pass this value with the x-amzn-access-token
        /// header when making subsequent calls to these restricted resources.
        /// </summary>
        [JsonProperty(PropertyName = "restrictedDataToken")]
        public string RestrictedDataToken { get; set; }

        /// <summary>
        /// Gets or sets the lifetime of the Restricted Data Token, in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "expiresIn")]
        public int? ExpiresIn { get; set; }

    }
}
