// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.ProductFees.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Price information for an item, used to estimate fees.
    /// </summary>
    public partial class PriceToEstimateFees
    {
        /// <summary>
        /// Initializes a new instance of the PriceToEstimateFees class.
        /// </summary>
        public PriceToEstimateFees()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PriceToEstimateFees class.
        /// </summary>
        /// <param name="listingPrice">The price of the item.</param>
        /// <param name="shipping">The shipping cost.</param>
        /// <param name="points">The number of Amazon Points offered with the
        /// purchase of an item.</param>
        public PriceToEstimateFees(MoneyType listingPrice, MoneyType shipping = default(MoneyType), Points points = default(Points))
        {
            ListingPrice = listingPrice;
            Shipping = shipping;
            Points = points;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the price of the item.
        /// </summary>
        [JsonProperty(PropertyName = "ListingPrice")]
        public MoneyType ListingPrice { get; set; }

        /// <summary>
        /// Gets or sets the shipping cost.
        /// </summary>
        [JsonProperty(PropertyName = "Shipping")]
        public MoneyType Shipping { get; set; }

        /// <summary>
        /// Gets or sets the number of Amazon Points offered with the purchase
        /// of an item.
        /// </summary>
        [JsonProperty(PropertyName = "Points")]
        public Points Points { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ListingPrice == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ListingPrice");
            }
        }
    }
}
