// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Orders.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Tax information about the buyer.
    /// </summary>
    public partial class BuyerTaxInfo
    {
        /// <summary>
        /// Initializes a new instance of the BuyerTaxInfo class.
        /// </summary>
        public BuyerTaxInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BuyerTaxInfo class.
        /// </summary>
        /// <param name="companyLegalName">The legal name of the
        /// company.</param>
        /// <param name="taxingRegion">The country or region imposing the
        /// tax.</param>
        /// <param name="taxClassifications">A list of tax classifications that
        /// apply to the order.</param>
        public BuyerTaxInfo(string companyLegalName = default(string), string taxingRegion = default(string), IList<TaxClassification> taxClassifications = default(IList<TaxClassification>))
        {
            CompanyLegalName = companyLegalName;
            TaxingRegion = taxingRegion;
            TaxClassifications = taxClassifications;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the legal name of the company.
        /// </summary>
        [JsonProperty(PropertyName = "CompanyLegalName")]
        public string CompanyLegalName { get; set; }

        /// <summary>
        /// Gets or sets the country or region imposing the tax.
        /// </summary>
        [JsonProperty(PropertyName = "TaxingRegion")]
        public string TaxingRegion { get; set; }

        /// <summary>
        /// Gets or sets a list of tax classifications that apply to the order.
        /// </summary>
        [JsonProperty(PropertyName = "TaxClassifications")]
        public IList<TaxClassification> TaxClassifications { get; set; }

    }
}
