// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Orders.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The tax classification for the order.
    /// </summary>
    public partial class TaxClassification
    {
        /// <summary>
        /// Initializes a new instance of the TaxClassification class.
        /// </summary>
        public TaxClassification()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaxClassification class.
        /// </summary>
        /// <param name="name">The type of tax.</param>
        /// <param name="value">The buyer's tax identifier.</param>
        public TaxClassification(string name = default(string), string value = default(string))
        {
            Name = name;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the type of tax.
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the buyer's tax identifier.
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

    }
}
