// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Feeds.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateFeedResult
    {
        /// <summary>
        /// Initializes a new instance of the CreateFeedResult class.
        /// </summary>
        public CreateFeedResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateFeedResult class.
        /// </summary>
        /// <param name="feedId">The identifier for the feed. This identifier
        /// is unique only in combination with a seller ID.</param>
        public CreateFeedResult(string feedId)
        {
            FeedId = feedId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the identifier for the feed. This identifier is unique
        /// only in combination with a seller ID.
        /// </summary>
        [JsonProperty(PropertyName = "feedId")]
        public string FeedId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FeedId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FeedId");
            }
        }
    }
}
