// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Reports.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A list of report schedules.
    /// </summary>
    public partial class ReportScheduleList
    {
        /// <summary>
        /// Initializes a new instance of the ReportScheduleList class.
        /// </summary>
        public ReportScheduleList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReportScheduleList class.
        /// </summary>
        public ReportScheduleList(IList<ReportSchedule> reportSchedules)
        {
            ReportSchedules = reportSchedules;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reportSchedules")]
        public IList<ReportSchedule> ReportSchedules { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ReportSchedules == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ReportSchedules");
            }
            if (ReportSchedules != null)
            {
                foreach (var element in ReportSchedules)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
