// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Orders.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Buyer information
    /// </summary>
    public partial class BuyerInfo
    {
        /// <summary>
        /// Initializes a new instance of the BuyerInfo class.
        /// </summary>
        public BuyerInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BuyerInfo class.
        /// </summary>
        /// <param name="buyerEmail">The anonymized email address of the
        /// buyer.</param>
        /// <param name="buyerName">The name of the buyer.</param>
        /// <param name="buyerCounty">The county of the buyer.</param>
        /// <param name="buyerTaxInfo">Tax information about the buyer.</param>
        /// <param name="purchaseOrderNumber">The purchase order (PO) number
        /// entered by the buyer at checkout. Returned only for orders where
        /// the buyer entered a PO number at checkout.</param>
        public BuyerInfo(string buyerEmail = default(string), string buyerName = default(string), string buyerCounty = default(string), BuyerTaxInfo buyerTaxInfo = default(BuyerTaxInfo), string purchaseOrderNumber = default(string))
        {
            BuyerEmail = buyerEmail;
            BuyerName = buyerName;
            BuyerCounty = buyerCounty;
            BuyerTaxInfo = buyerTaxInfo;
            PurchaseOrderNumber = purchaseOrderNumber;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the anonymized email address of the buyer.
        /// </summary>
        [JsonProperty(PropertyName = "BuyerEmail")]
        public string BuyerEmail { get; set; }

        /// <summary>
        /// Gets or sets the name of the buyer.
        /// </summary>
        [JsonProperty(PropertyName = "BuyerName")]
        public string BuyerName { get; set; }

        /// <summary>
        /// Gets or sets the county of the buyer.
        /// </summary>
        [JsonProperty(PropertyName = "BuyerCounty")]
        public string BuyerCounty { get; set; }

        /// <summary>
        /// Gets or sets tax information about the buyer.
        /// </summary>
        [JsonProperty(PropertyName = "BuyerTaxInfo")]
        public BuyerTaxInfo BuyerTaxInfo { get; set; }

        /// <summary>
        /// Gets or sets the purchase order (PO) number entered by the buyer at
        /// checkout. Returned only for orders where the buyer entered a PO
        /// number at checkout.
        /// </summary>
        [JsonProperty(PropertyName = "PurchaseOrderNumber")]
        public string PurchaseOrderNumber { get; set; }

    }
}
