// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.Orders.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The error response schema for the UpdateShipmentStatus operation.
    /// </summary>
    public partial class UpdateShipmentStatusErrorResponse
    {
        /// <summary>
        /// Initializes a new instance of the UpdateShipmentStatusErrorResponse
        /// class.
        /// </summary>
        public UpdateShipmentStatusErrorResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateShipmentStatusErrorResponse
        /// class.
        /// </summary>
        /// <param name="errors">One or more unexpected errors occurred during
        /// the UpdateShipmentStatus operation.</param>
        public UpdateShipmentStatusErrorResponse(IList<Error> errors = default(IList<Error>))
        {
            Errors = errors;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets one or more unexpected errors occurred during the
        /// UpdateShipmentStatus operation.
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<Error> Errors { get; set; }

    }
}
