// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.CatalogItems.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Sales ranks of an Amazon catalog item for the indicated Amazon
    /// marketplace.
    /// </summary>
    public partial class ItemSalesRanksByMarketplace
    {
        /// <summary>
        /// Initializes a new instance of the ItemSalesRanksByMarketplace
        /// class.
        /// </summary>
        public ItemSalesRanksByMarketplace()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemSalesRanksByMarketplace
        /// class.
        /// </summary>
        /// <param name="marketplaceId">Amazon marketplace identifier.</param>
        /// <param name="ranks">Sales ranks of an Amazon catalog item for an
        /// Amazon marketplace.</param>
        public ItemSalesRanksByMarketplace(string marketplaceId, IList<ItemSalesRank> ranks)
        {
            MarketplaceId = marketplaceId;
            Ranks = ranks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets amazon marketplace identifier.
        /// </summary>
        [JsonProperty(PropertyName = "marketplaceId")]
        public string MarketplaceId { get; set; }

        /// <summary>
        /// Gets or sets sales ranks of an Amazon catalog item for an Amazon
        /// marketplace.
        /// </summary>
        [JsonProperty(PropertyName = "ranks")]
        public IList<ItemSalesRank> Ranks { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (MarketplaceId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MarketplaceId");
            }
            if (Ranks == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Ranks");
            }
            if (Ranks != null)
            {
                foreach (var element in Ranks)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
