// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.CatalogItems.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Vendor details associated with an Amazon catalog item for the indicated
    /// Amazon marketplace.
    /// </summary>
    public partial class ItemVendorDetailsByMarketplace
    {
        /// <summary>
        /// Initializes a new instance of the ItemVendorDetailsByMarketplace
        /// class.
        /// </summary>
        public ItemVendorDetailsByMarketplace()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemVendorDetailsByMarketplace
        /// class.
        /// </summary>
        /// <param name="marketplaceId">Amazon marketplace identifier.</param>
        /// <param name="brandCode">Brand code associated with an Amazon
        /// catalog item.</param>
        /// <param name="categoryCode">Product category associated with an
        /// Amazon catalog item.</param>
        /// <param name="manufacturerCode">Manufacturer code associated with an
        /// Amazon catalog item.</param>
        /// <param name="manufacturerCodeParent">Parent vendor code of the
        /// manufacturer code.</param>
        /// <param name="productGroup">Product group associated with an Amazon
        /// catalog item.</param>
        /// <param name="replenishmentCategory">Replenishment category
        /// associated with an Amazon catalog item. Possible values include:
        /// 'ALLOCATED', 'BASIC_REPLENISHMENT', 'IN_SEASON',
        /// 'LIMITED_REPLENISHMENT', 'MANUFACTURER_OUT_OF_STOCK',
        /// 'NEW_PRODUCT', 'NON_REPLENISHABLE', 'NON_STOCKUPABLE', 'OBSOLETE',
        /// 'PLANNED_REPLENISHMENT'</param>
        /// <param name="subcategoryCode">Product subcategory associated with
        /// an Amazon catalog item.</param>
        public ItemVendorDetailsByMarketplace(string marketplaceId, string brandCode = default(string), string categoryCode = default(string), string manufacturerCode = default(string), string manufacturerCodeParent = default(string), string productGroup = default(string), string replenishmentCategory = default(string), string subcategoryCode = default(string))
        {
            MarketplaceId = marketplaceId;
            BrandCode = brandCode;
            CategoryCode = categoryCode;
            ManufacturerCode = manufacturerCode;
            ManufacturerCodeParent = manufacturerCodeParent;
            ProductGroup = productGroup;
            ReplenishmentCategory = replenishmentCategory;
            SubcategoryCode = subcategoryCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets amazon marketplace identifier.
        /// </summary>
        [JsonProperty(PropertyName = "marketplaceId")]
        public string MarketplaceId { get; set; }

        /// <summary>
        /// Gets or sets brand code associated with an Amazon catalog item.
        /// </summary>
        [JsonProperty(PropertyName = "brandCode")]
        public string BrandCode { get; set; }

        /// <summary>
        /// Gets or sets product category associated with an Amazon catalog
        /// item.
        /// </summary>
        [JsonProperty(PropertyName = "categoryCode")]
        public string CategoryCode { get; set; }

        /// <summary>
        /// Gets or sets manufacturer code associated with an Amazon catalog
        /// item.
        /// </summary>
        [JsonProperty(PropertyName = "manufacturerCode")]
        public string ManufacturerCode { get; set; }

        /// <summary>
        /// Gets or sets parent vendor code of the manufacturer code.
        /// </summary>
        [JsonProperty(PropertyName = "manufacturerCodeParent")]
        public string ManufacturerCodeParent { get; set; }

        /// <summary>
        /// Gets or sets product group associated with an Amazon catalog item.
        /// </summary>
        [JsonProperty(PropertyName = "productGroup")]
        public string ProductGroup { get; set; }

        /// <summary>
        /// Gets or sets replenishment category associated with an Amazon
        /// catalog item. Possible values include: 'ALLOCATED',
        /// 'BASIC_REPLENISHMENT', 'IN_SEASON', 'LIMITED_REPLENISHMENT',
        /// 'MANUFACTURER_OUT_OF_STOCK', 'NEW_PRODUCT', 'NON_REPLENISHABLE',
        /// 'NON_STOCKUPABLE', 'OBSOLETE', 'PLANNED_REPLENISHMENT'
        /// </summary>
        [JsonProperty(PropertyName = "replenishmentCategory")]
        public string ReplenishmentCategory { get; set; }

        /// <summary>
        /// Gets or sets product subcategory associated with an Amazon catalog
        /// item.
        /// </summary>
        [JsonProperty(PropertyName = "subcategoryCode")]
        public string SubcategoryCode { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (MarketplaceId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MarketplaceId");
            }
        }
    }
}
