// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.CatalogItems.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Sales rank of an Amazon catalog item by classification.
    /// </summary>
    public partial class ItemClassificationSalesRank
    {
        /// <summary>
        /// Initializes a new instance of the ItemClassificationSalesRank
        /// class.
        /// </summary>
        public ItemClassificationSalesRank()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemClassificationSalesRank
        /// class.
        /// </summary>
        /// <param name="classificationId">Identifier of the classification
        /// associated with the sales rank.</param>
        /// <param name="title">Title, or name, of the sales rank.</param>
        /// <param name="rank">Sales rank value.</param>
        /// <param name="link">Corresponding Amazon retail website link, or
        /// URL, for the sales rank.</param>
        public ItemClassificationSalesRank(string classificationId, string title, int rank, string link = default(string))
        {
            ClassificationId = classificationId;
            Title = title;
            Link = link;
            Rank = rank;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets identifier of the classification associated with the
        /// sales rank.
        /// </summary>
        [JsonProperty(PropertyName = "classificationId")]
        public string ClassificationId { get; set; }

        /// <summary>
        /// Gets or sets title, or name, of the sales rank.
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets corresponding Amazon retail website link, or URL, for
        /// the sales rank.
        /// </summary>
        [JsonProperty(PropertyName = "link")]
        public string Link { get; set; }

        /// <summary>
        /// Gets or sets sales rank value.
        /// </summary>
        [JsonProperty(PropertyName = "rank")]
        public int Rank { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ClassificationId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ClassificationId");
            }
            if (Title == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Title");
            }
        }
    }
}
