// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.CatalogItems.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Variation theme indicating the combination of Amazon item catalog
    /// attributes that define the variation family.
    /// </summary>
    public partial class ItemVariationTheme
    {
        /// <summary>
        /// Initializes a new instance of the ItemVariationTheme class.
        /// </summary>
        public ItemVariationTheme()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemVariationTheme class.
        /// </summary>
        /// <param name="attributes">Names of the Amazon catalog item
        /// attributes associated with the variation theme.</param>
        /// <param name="theme">Variation theme indicating the combination of
        /// Amazon item catalog attributes that define the variation
        /// family.</param>
        public ItemVariationTheme(IList<string> attributes = default(IList<string>), string theme = default(string))
        {
            Attributes = attributes;
            Theme = theme;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets names of the Amazon catalog item attributes associated
        /// with the variation theme.
        /// </summary>
        [JsonProperty(PropertyName = "attributes")]
        public IList<string> Attributes { get; set; }

        /// <summary>
        /// Gets or sets variation theme indicating the combination of Amazon
        /// item catalog attributes that define the variation family.
        /// </summary>
        [JsonProperty(PropertyName = "theme")]
        public string Theme { get; set; }

    }
}
