// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.CatalogItems.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// When a request produces a response that exceeds the `pageSize`,
    /// pagination occurs. This means the response is divided into individual
    /// pages. To retrieve the next page or the previous page, you must pass
    /// the `nextToken` value or the `previousToken` value as the `pageToken`
    /// parameter in the next request. When you receive the last page, there
    /// will be no `nextToken` key in the pagination object.
    /// </summary>
    public partial class Pagination
    {
        /// <summary>
        /// Initializes a new instance of the Pagination class.
        /// </summary>
        public Pagination()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Pagination class.
        /// </summary>
        /// <param name="nextToken">A token that can be used to fetch the next
        /// page.</param>
        /// <param name="previousToken">A token that can be used to fetch the
        /// previous page.</param>
        public Pagination(string nextToken = default(string), string previousToken = default(string))
        {
            NextToken = nextToken;
            PreviousToken = previousToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a token that can be used to fetch the next page.
        /// </summary>
        [JsonProperty(PropertyName = "nextToken")]
        public string NextToken { get; set; }

        /// <summary>
        /// Gets or sets a token that can be used to fetch the previous page.
        /// </summary>
        [JsonProperty(PropertyName = "previousToken")]
        public string PreviousToken { get; set; }

    }
}
