// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.FulfillmentInbound.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BillOfLadingDownloadURL
    {
        /// <summary>
        /// Initializes a new instance of the BillOfLadingDownloadURL class.
        /// </summary>
        public BillOfLadingDownloadURL()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BillOfLadingDownloadURL class.
        /// </summary>
        /// <param name="downloadURL">URL to download the bill of lading for
        /// the package. Note: The URL will only be valid for 15
        /// seconds</param>
        public BillOfLadingDownloadURL(string downloadURL = default(string))
        {
            DownloadURL = downloadURL;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets URL to download the bill of lading for the package.
        /// Note: The URL will only be valid for 15 seconds
        /// </summary>
        [JsonProperty(PropertyName = "DownloadURL")]
        public string DownloadURL { get; set; }

    }
}
