// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.FulfillmentInbound.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CommonTransportResult
    {
        /// <summary>
        /// Initializes a new instance of the CommonTransportResult class.
        /// </summary>
        public CommonTransportResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CommonTransportResult class.
        /// </summary>
        public CommonTransportResult(TransportResult transportResult = default(TransportResult))
        {
            TransportResult = transportResult;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransportResult")]
        public TransportResult TransportResult { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (TransportResult != null)
            {
                TransportResult.Validate();
            }
        }
    }
}
