// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.FulfillmentInbound.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetInboundGuidanceResult
    {
        /// <summary>
        /// Initializes a new instance of the GetInboundGuidanceResult class.
        /// </summary>
        public GetInboundGuidanceResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetInboundGuidanceResult class.
        /// </summary>
        public GetInboundGuidanceResult(IList<SKUInboundGuidance> sKUInboundGuidanceList = default(IList<SKUInboundGuidance>), IList<InvalidSKU> invalidSKUList = default(IList<InvalidSKU>), IList<ASINInboundGuidance> aSINInboundGuidanceList = default(IList<ASINInboundGuidance>), IList<InvalidASIN> invalidASINList = default(IList<InvalidASIN>))
        {
            SKUInboundGuidanceList = sKUInboundGuidanceList;
            InvalidSKUList = invalidSKUList;
            ASINInboundGuidanceList = aSINInboundGuidanceList;
            InvalidASINList = invalidASINList;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SKUInboundGuidanceList")]
        public IList<SKUInboundGuidance> SKUInboundGuidanceList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvalidSKUList")]
        public IList<InvalidSKU> InvalidSKUList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ASINInboundGuidanceList")]
        public IList<ASINInboundGuidance> ASINInboundGuidanceList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvalidASINList")]
        public IList<InvalidASIN> InvalidASINList { get; set; }

    }
}
