// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.FulfillmentInbound.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetPrepInstructionsResult
    {
        /// <summary>
        /// Initializes a new instance of the GetPrepInstructionsResult class.
        /// </summary>
        public GetPrepInstructionsResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetPrepInstructionsResult class.
        /// </summary>
        public GetPrepInstructionsResult(IList<SKUPrepInstructions> sKUPrepInstructionsList = default(IList<SKUPrepInstructions>), IList<InvalidSKU> invalidSKUList = default(IList<InvalidSKU>), IList<ASINPrepInstructions> aSINPrepInstructionsList = default(IList<ASINPrepInstructions>), IList<InvalidASIN> invalidASINList = default(IList<InvalidASIN>))
        {
            SKUPrepInstructionsList = sKUPrepInstructionsList;
            InvalidSKUList = invalidSKUList;
            ASINPrepInstructionsList = aSINPrepInstructionsList;
            InvalidASINList = invalidASINList;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SKUPrepInstructionsList")]
        public IList<SKUPrepInstructions> SKUPrepInstructionsList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvalidSKUList")]
        public IList<InvalidSKU> InvalidSKUList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ASINPrepInstructionsList")]
        public IList<ASINPrepInstructions> ASINPrepInstructionsList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvalidASINList")]
        public IList<InvalidASIN> InvalidASINList { get; set; }

    }
}
