// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.FulfillmentInbound.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Dimension and weight information for the package.
    /// </summary>
    public partial class PartneredSmallParcelPackageInput
    {
        /// <summary>
        /// Initializes a new instance of the PartneredSmallParcelPackageInput
        /// class.
        /// </summary>
        public PartneredSmallParcelPackageInput()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PartneredSmallParcelPackageInput
        /// class.
        /// </summary>
        public PartneredSmallParcelPackageInput(Dimensions dimensions, Weight weight)
        {
            Dimensions = dimensions;
            Weight = weight;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Dimensions")]
        public Dimensions Dimensions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Weight")]
        public Weight Weight { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Dimensions == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Dimensions");
            }
            if (Weight == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Weight");
            }
            if (Dimensions != null)
            {
                Dimensions.Validate();
            }
            if (Weight != null)
            {
                Weight.Validate();
            }
        }
    }
}
