// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.ProductPricing.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The number of offer listings with the specified condition.
    /// </summary>
    public partial class OfferListingCountType
    {
        /// <summary>
        /// Initializes a new instance of the OfferListingCountType class.
        /// </summary>
        public OfferListingCountType()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OfferListingCountType class.
        /// </summary>
        /// <param name="count">The number of offer listings.</param>
        /// <param name="condition">The condition of the item.</param>
        public OfferListingCountType(int count, string condition)
        {
            Count = count;
            Condition = condition;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the number of offer listings.
        /// </summary>
        [JsonProperty(PropertyName = "Count")]
        public int Count { get; set; }

        /// <summary>
        /// Gets or sets the condition of the item.
        /// </summary>
        [JsonProperty(PropertyName = "condition")]
        public string Condition { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Condition == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Condition");
            }
        }
    }
}
