// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IL.Library.Amazon.SPAPI.ProductPricing.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Amazon Prime information.
    /// </summary>
    public partial class PrimeInformationType
    {
        /// <summary>
        /// Initializes a new instance of the PrimeInformationType class.
        /// </summary>
        public PrimeInformationType()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PrimeInformationType class.
        /// </summary>
        /// <param name="isPrime">Indicates whether the offer is an Amazon
        /// Prime offer.</param>
        /// <param name="isNationalPrime">Indicates whether the offer is an
        /// Amazon Prime offer throughout the entire marketplace where it is
        /// listed.</param>
        public PrimeInformationType(bool isPrime, bool isNationalPrime)
        {
            IsPrime = isPrime;
            IsNationalPrime = isNationalPrime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets indicates whether the offer is an Amazon Prime offer.
        /// </summary>
        [JsonProperty(PropertyName = "IsPrime")]
        public bool IsPrime { get; set; }

        /// <summary>
        /// Gets or sets indicates whether the offer is an Amazon Prime offer
        /// throughout the entire marketplace where it is listed.
        /// </summary>
        [JsonProperty(PropertyName = "IsNationalPrime")]
        public bool IsNationalPrime { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
